package helpers;

import enums.TokenQueryParamEnum;
import java.lang.reflect.Method;
import org.testng.annotations.DataProvider;

public class TokenQueryParamPositiveDataHelper {
  @DataProvider(name = "token_dataProvider")
  public static Object[][] token_dataProvider(Method m) {

    switch (m.getName()) {
      case "getTokensByOneParamTest":
        return new Object[][] {
          {TokenQueryParamEnum.ID_ENUM},
          {TokenQueryParamEnum.CHAIN_ID_ENUM},
          {TokenQueryParamEnum.ADDRESS_ENUM},
          {TokenQueryParamEnum.NAME_ENUM},
          {TokenQueryParamEnum.SYMBOL_ENUM},
          {TokenQueryParamEnum.TYPE_ENUM},
          {TokenQueryParamEnum.TOTAL_SUPPLY_ENUM},
          {TokenQueryParamEnum.DECIMALS_ENUM},
          {TokenQueryParamEnum.BASE_URI_ENUM},
          {TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM},
          {TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM},
          {TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM},
          {TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM},
          {TokenQueryParamEnum.TRANSFER_COUNT_ENUM},
          {TokenQueryParamEnum.TOKEN_TRAITS_ENUM},
          {TokenQueryParamEnum.TOKEN_BALANCE_ENUM}
        };

      case "getTokensByTwoParamsTest":
        return new Object[][] {
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.CHAIN_ID_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.NAME_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.ADDRESS_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.SYMBOL_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.TYPE_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.TOTAL_SUPPLY_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.DECIMALS_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.BASE_URI_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.TRANSFER_COUNT_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.TOKEN_TRAITS_ENUM},
          {TokenQueryParamEnum.ID_ENUM, TokenQueryParamEnum.TOKEN_BALANCE_ENUM}
        };

      case "getTokensByThreeParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.TYPE_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByFourParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.TYPE_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByFiveParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensBySixParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensBySevenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByEightParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByNineParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByTenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByElevenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByTwelveParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByThirteenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByFourteenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          }
        };

      case "getTokensByFifteenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM
          },
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          }
        };

      case "getTokensBySixteenParamsTest":
        return new Object[][] {
          {
            TokenQueryParamEnum.ID_ENUM,
            TokenQueryParamEnum.CHAIN_ID_ENUM,
            TokenQueryParamEnum.NAME_ENUM,
            TokenQueryParamEnum.SYMBOL_ENUM,
            TokenQueryParamEnum.TYPE_ENUM,
            TokenQueryParamEnum.TOTAL_SUPPLY_ENUM,
            TokenQueryParamEnum.DECIMALS_ENUM,
            TokenQueryParamEnum.BASE_URI_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_TIMESTAMP_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_BLOCK_ENUM,
            TokenQueryParamEnum.LAST_TRANSFER_HASH_ENUM,
            TokenQueryParamEnum.CURRENT_HOLDER_COUNT_ENUM,
            TokenQueryParamEnum.TRANSFER_COUNT_ENUM,
            TokenQueryParamEnum.TOKEN_TRAITS_ENUM,
            TokenQueryParamEnum.TOKEN_BALANCE_ENUM,
            TokenQueryParamEnum.ADDRESS_ENUM
          }
        };

      default:
        return new Object[][] {};
    }
  }
}
